version: "3.8"

volumes:
  mongodb_data:
  elastic_data:

services:

  # MongoDB database service
  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - mongodb_data:/data/db
    #restart: on-failure # make this container restart on failure

  # Elasticsearch search server service
  elastic:
    image: blacktop/elasticsearch:latest
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    #restart: on-failure # make this container restart on failure

  # the actual VedaWeb application, built based on Dockerfile
  app:
    build: .
    #restart: on-failure # make this container restart on failure
    ports:
      - "8081:8080" # the application will be served via HTTP on host port 8081
    depends_on:
      - mongodb
      - elastic