theme: jekyll-theme-minimal
title: VedaWeb
description: This DFG-funded project provides a web-based, open-access platform in order to facilitate linguistic research on old indic texts.
logo: logo.png
show_downloads: false
